version: '3'

services:
  s3:
    image: minio/minio:latest
    container_name: s3
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    volumes:
      - minio-storage:/data
    networks:
      - app_net

networks:
  app_net:
    external: true

volumes:
  minio-storage: