ARG VARIANT=3-bullseye
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}

ENV PYTHONUNBUFFERED=1

EXPOSE 8000/tcp

ENV APP_HOME=/home/app/admin
RUN mkdir -p $APP_HOME
RUN mkdir -p $APP_HOME/static
WORKDIR $APP_HOME

RUN apt-get -y update --no-install-recommends \
    && apt-get -y install --no-install-recommends \
    curl \
    git \
    && apt-get autoremove -y \
    && apt-get clean -y

# get poetry and dependancies
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="${PATH}:/root/.local/bin"
COPY poetry.lock .
COPY pyproject.toml .
RUN poetry install

COPY ./lizaalert-backend .

CMD ["poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]