version: '3'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./services/postgres/.env

  backend:
    image: cr.yandex/crpph3mqagnq011414qt/lizaalert_backend:latest
    restart: always
    env_file:
      - ./lizaalert-backend/.env
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - postgres

  nginx:
    image: nginx:1.22-alpine
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx.conf
      - ./services/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    ports:
      - "8000:8000"
    depends_on:
      - backend

volumes:
  postgres_volume:
  static_volume:
  media_volume:
