version: '3'

services:
  postgres:
    build: ./services/postgres
    container_name: la_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lizaalert
    ports:
      - 5432

  tests:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: tests
    command: pytest
    environment:
      - DB_NAME=lizaalert
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
