FROM python:3.10.0-alpine

EXPOSE 8000/tcp

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ARG YOUR_ENV

ENV YOUR_ENV=${YOUR_ENV} \
  PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  POETRY_VERSION=1.1.12

RUN apk update --no-cache \
  && apk add build-base libffi-dev zlib-dev jpeg-dev libxslt-dev postgresql-dev libpq freetype-dev --no-cache --virtual .build-deps \
  && pip install --no-cache-dir --upgrade pip \
  && pip install "poetry==$POETRY_VERSION"

WORKDIR /app
COPY poetry.lock /app/poetry.lock
COPY pyproject.toml /app/pyproject.toml

RUN poetry config virtualenvs.create false \
  && poetry install $(test "$YOUR_ENV" == production && echo "--no-dev") --no-interaction --no-ansi

COPY services/wait_for_pg.py /app/wait_for_pg.py
COPY lizaalert-backend /app/
COPY tests/tests/ /app/tests

ENTRYPOINT python3 wait_for_pg.py; python3 make_db_pg.py; pytest -s -v -o log_cli=true --log-cli-level=INFO tests/
