# Generated by Django 3.2.12 on 2022-05-23 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursestatus'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteercourse',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_status', to='courses.coursestatus', verbose_name='Статус'),
        ),
    ]
