# Generated by Django 3.2.12 on 2022-05-26 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('users', '0002_alter_volunteercourse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteercourse',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volunteer_courses', to='courses.coursestatus', verbose_name='Статус'),
        ),
    ]
