# Generated by Django 3.2.12 on 2022-06-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_volunteercourse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('Новичок', 'novice'), ('Бывалый', 'experienced'), ('Профессионал', 'professional')], max_length=20, verbose_name='Наименование уровня'),
        ),
    ]
