# Generated by Django 3.2.12 on 2022-06-14 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_volunteercourse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='badges',
            field=models.ManyToManyField(blank=True, null=True, related_name='volunteers', through='users.VolunteerBadge', to='users.Badge', verbose_name='Значки'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='level',
            field=models.ManyToManyField(blank=True, null=True, related_name='volunteers', through='users.VolunteerLevel', to='users.Level', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='users.location', verbose_name='Географический регион'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
