# Generated by Django 3.2.12 on 2022-07-09 19:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220614_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='level',
            field=models.ManyToManyField(blank=True, null=True, related_name='volunteers', through='users.VolunteerLevel', to='users.Level', verbose_name='Уровени'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
    ]
