# Generated by Django 3.2.18 on 2023-03-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='format',
            new_name='course_format',
        ),
    ]
