# Generated by Django 3.2.18 on 2023-04-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_format_course_course_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faq',
            field=models.TextField(blank=True, verbose_name='FAQ'),
        ),
    ]
