# Generated by Django 3.2.20 on 2023-08-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CourseKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=1000, verbose_name='Ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название умения')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание умения')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='course',
            name='knowledge',
        ),
        migrations.AddConstraint(
            model_name='knowledge',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_knowledge'),
        ),
        migrations.AddConstraint(
            model_name='faq',
            constraint=models.UniqueConstraint(fields=('question',), name='unique_question'),
        ),
        migrations.AddField(
            model_name='courseknowledge',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseknowledge',
            name='knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.knowledge'),
        ),
        migrations.AddField(
            model_name='coursefaq',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursefaq',
            name='faq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.faq'),
        ),
        migrations.AddField(
            model_name='course',
            name='faq',
            field=models.ManyToManyField(through='courses.CourseFaq', to='courses.FAQ', verbose_name='Часто задаваемые вопросы'),
        ),
        migrations.AddField(
            model_name='course',
            name='knowledge',
            field=models.ManyToManyField(through='courses.CourseKnowledge', to='courses.Knowledge', verbose_name='Умения'),
        ),
    ]
