# Generated by Django 3.2.20 on 2023-08-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20230820_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='knowledge',
            options={'verbose_name': 'Умение', 'verbose_name_plural': 'Умения'},
        ),
    ]
