# Generated by Django 3.2.20 on 2023-09-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_knowledge_faq_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestatus',
            name='type_status',
            field=models.CharField(choices=[('draft', 'в разработке'), ('published', 'опубликован'), ('archive', 'в архиве')], default='draft', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='coursestatus',
            name='slug',
            field=models.CharField(editable=False, max_length=50, verbose_name='Слаг курса'),
        ),
        migrations.AddConstraint(
            model_name='coursestatus',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_slug_status'),
        ),
    ]
