# Generated by Django 3.2.20 on 2023-08-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20230820_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faq',
            field=models.ManyToManyField(null=True, through='courses.CourseFaq', to='courses.FAQ', verbose_name='Часто задаваемые вопросы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='knowledge',
            field=models.ManyToManyField(null=True, through='courses.CourseKnowledge', to='courses.Knowledge', verbose_name='Умения'),
        ),
    ]
