# Generated by Django 3.2.20 on 2023-09-29 08:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20230918_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterlesson',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='chapterlesson',
            name='lesson',
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('order_number',), 'verbose_name': 'глава', 'verbose_name_plural': 'глава'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('order_number',), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='lessons',
        ),
        migrations.AddField(
            model_name='chapter',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='порядковый номер главы'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='courses.chapter', verbose_name='уроки главы'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='порядковый номер урока'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='coursefaq',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='coursefaq',
            name='faq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.faq'),
        ),
        migrations.AlterField(
            model_name='courseknowledge',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='courseknowledge',
            name='knowledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.knowledge'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('order_number', 'course'), name='unique_order_number'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('order_number', 'chapter_id'), name='unique_lesson_order_number'),
        ),
        migrations.DeleteModel(
            name='ChapterLesson',
        ),
    ]
