# Generated by Django 3.2.20 on 2023-10-16 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20231006_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogressstatus',
            name='userlessonprogress',
            field=models.CharField(choices=[('0', 'Не начат'), ('1', 'Начат'), ('2', 'Пройден')], default=0, max_length=20, verbose_name='прогресс урока'),
        ),
        migrations.AlterField(
            model_name='lessonprogressstatus',
            name='version_number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер версии урока'),
        ),
    ]
