# Generated by Django 3.2.20 on 2023-10-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231027_1728'),
        ('courses', '0011_auto_20231016_1943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseStatus',
        ),
    ]
