# Generated by Django 3.2.20 on 2023-10-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231026_1123'),
        ('courses', '0011_auto_20231016_1943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseStatus',
        ),
        migrations.AlterModelOptions(
            name='chapterprogressstatus',
            options={'ordering': ('user',), 'verbose_name': 'Прогресс по главе', 'verbose_name_plural': 'Прогресс по главам'},
        ),
        migrations.AlterModelOptions(
            name='courseprogressstatus',
            options={'ordering': ('user',), 'verbose_name': 'Прогресс по курсу', 'verbose_name_plural': 'Прогресс по курсам'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogressstatus',
            options={'ordering': ('user',), 'verbose_name': 'Прогресс по уроку', 'verbose_name_plural': 'Прогресс по урокам'},
        ),
        migrations.AddField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('Draft', 'в разработке'), ('Published', 'опубликован'), ('Archive', 'в архиве')], default='Draft', max_length=20, verbose_name='статус курса'),
        ),
        migrations.AlterField(
            model_name='chapterprogressstatus',
            name='userchapterprogress',
            field=models.CharField(choices=[('0', 'Не начата'), ('1', 'Начата'), ('2', 'Пройдена')], max_length=20, verbose_name='прогресс главы'),
        ),
    ]
