# Generated by Django 3.2.20 on 2023-10-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231027_1728'),
        ('courses', '0012_delete_coursestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterprogressstatus',
            options={'ordering': ('user',), 'verbose_name': 'Прогресс по главе', 'verbose_name_plural': 'Прогресс по главам'},
        ),
        migrations.AlterModelOptions(
            name='courseprogressstatus',
            options={'ordering': ('user',), 'verbose_name': 'Прогресс по курсу', 'verbose_name_plural': 'Прогресс по курсам'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogressstatus',
            options={'ordering': ('user',), 'verbose_name': 'Прогресс по уроку', 'verbose_name_plural': 'Прогресс по урокам'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_status',
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(0, 'в разработке'), (1, 'опубликован'), (2, 'в архиве')], default=0, verbose_name='статус курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.IntegerField(choices=[(0, 'В разработке'), (1, 'Готов'), (2, 'Опубликован')], default=0, verbose_name='статус урока'),
        ),
        migrations.AlterField(
            model_name='chapterprogressstatus',
            name='userchapterprogress',
            field=models.CharField(choices=[('0', 'Не начата'), ('1', 'Начата'), ('2', 'Пройдена')], max_length=20, verbose_name='прогресс главы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='faq',
            field=models.ManyToManyField(through='courses.CourseFaq', to='courses.FAQ', verbose_name='Часто задаваемые вопросы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='knowledge',
            field=models.ManyToManyField(through='courses.CourseKnowledge', to='courses.Knowledge', verbose_name='Умения'),
        ),
    ]
