# Generated by Django 3.2.20 on 2023-11-02 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20231027_1728'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chapter',
            name='unique_order_number',
        ),
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_lesson_order_number',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='порядковый номер главы'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='порядковый номер урока'),
        ),
    ]
