# Generated by Django 3.2.20 on 2023-11-28 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20231109_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order_number',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='порядковый номер'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order_number',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='порядковый номер'),
        ),
    ]
