# Generated by Django 3.2.20 on 2023-12-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20231128_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='enabled',
            field=models.CharField(choices=[('Enrolled', 'Запись активна'), ('NotEnrolled', 'Запись не активна')], default='Enrolled', max_length=20, verbose_name='статус записи на курс'),
        ),
    ]
