# Generated by Django 3.2.20 on 2023-12-25 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0016_alter_subscription_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='enabled',
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Записан на курс'), ('not_enrolled', 'Запись не активна'), ('in_progress', 'Курс проходится'), ('available', 'Курс доступен'), ('completed', 'Курс пройден')], default='enrolled', max_length=20, verbose_name='статус записи на курс'),
        ),
        migrations.AlterField(
            model_name='chapterprogressstatus',
            name='userchapterprogress',
            field=models.IntegerField(choices=[(0, 'Не начат'), (1, 'Начат'), (2, 'Пройден')], default=0, verbose_name='прогресс главы'),
        ),
        migrations.AlterField(
            model_name='courseprogressstatus',
            name='usercourseprogress',
            field=models.IntegerField(choices=[(0, 'Не начат'), (1, 'Начат'), (2, 'Пройден')], default=0, verbose_name='прогресс курса'),
        ),
        migrations.AlterField(
            model_name='lessonprogressstatus',
            name='userlessonprogress',
            field=models.IntegerField(choices=[(0, 'Не начат'), (1, 'Начат'), (2, 'Пройден')], default=0, verbose_name='прогресс урока'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
