# Generated by Django 3.2.20 on 2024-01-16 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20231227_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cohort_number', models.PositiveIntegerField(unique=True, verbose_name='Номер группы')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('students_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество студентов')),
                ('teacher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Преподаватель')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Группа курса',
                'verbose_name_plural': 'Группы курса',
                'ordering': ('cohort_number',),
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cohort', to='courses.cohort', verbose_name='Группа'),
        ),
    ]
