# Generated by Django 3.2.20 on 2024-01-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_Added_new_fields_in_cohort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'verbose_name': 'Группа курса', 'verbose_name_plural': 'Группы курса'},
        ),
        migrations.AlterField(
            model_name='cohort',
            name='cohort_number',
            field=models.PositiveIntegerField(verbose_name='Номер группы'),
        ),
    ]
