# Generated by Django 3.2.20 on 2024-01-26 11:29

from django.db import migrations, models
import django.db.models.deletion


def populate_subscription(apps, schema_editor):
    progresses = [
        (apps.get_model('courses', 'CourseProgressStatus'), 'course', lambda obj: obj.course),
        (apps.get_model('courses', 'LessonProgressStatus'), 'lesson__chapter__course', lambda obj: obj.lesson.chapter.course),
        (apps.get_model('courses', 'ChapterProgressStatus'), 'chapter__course', lambda obj: obj.chapter.course),
        ]
    Subscription = apps.get_model('courses', 'Subscription')
    for model, sel_related, get_course_func in progresses:
        queryset = model.objects.select_related(sel_related).all()
        for obj in queryset:
            course = get_course_func(obj)
            try:
                subscription = Subscription.objects.get(user_id=obj.user_id, course=course)
            except Subscription.DoesNotExist:
                subscription = Subscription.objects.create(user_id=obj.user_id, course=course)
            obj.subscription_id = subscription.id
            obj.save(update_fields=['subscription_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20240119_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogressstatus',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='courses.subscription', verbose_name='Подписка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapterprogressstatus',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to='courses.subscription', verbose_name='Подписка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonprogressstatus',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='courses.subscription', verbose_name='Подписка'),
            preserve_default=False,
        ),

        migrations.RunPython(populate_subscription),

    ]
