# Generated by Django 3.2.20 on 2024-01-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_Update_cohort_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_user_course',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('cohort', 'course'), name='unique_cohort_course'),
        ),
    ]
