# Generated by Django 3.2.23 on 2024-01-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20240126_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterprogressstatus',
            options={'ordering': ('subscription',), 'verbose_name': 'Прогресс по главе', 'verbose_name_plural': 'Прогресс по главам'},
        ),
        migrations.AlterModelOptions(
            name='courseprogressstatus',
            options={'ordering': ('subscription',), 'verbose_name': 'Прогресс по курсу', 'verbose_name_plural': 'Прогресс по курсам'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogressstatus',
            options={'ordering': ('subscription',), 'verbose_name': 'Прогресс по уроку', 'verbose_name_plural': 'Прогресс по урокам'},
        ),
        migrations.RemoveField(
            model_name='chapterprogressstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='courseprogressstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lessonprogressstatus',
            name='user',
        ),
    ]
