# Generated by Django 3.2.23 on 2024-02-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_Created_model_cohort'),
        ('courses', '0020_auto_20240130_2006'),
    ]

    operations = [
    ]
