# Generated by Django 3.2.23 on 2024-02-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20240202_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.AddField(
            model_name='cohort',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Максимальное количество студентов'),
        ),
    ]
