# Generated by Django 3.2.23 on 2024-02-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_Created_model_cohort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.AddField(
            model_name='cohort',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Не заполняйте это поле, если хотите, чтобы группа была доступна всегда.', null=True, verbose_name='Максимальное количество студентов'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(blank=True, help_text='Не заполняйте это поле, если хотите, чтобы группа была доступна всегда.', null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='start_date',
            field=models.DateField(blank=True, help_text='Не заполняйте это поле, если хотите, чтобы группа была доступна всегда.', null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='students_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Текущее количество студентов'),
        ),
    ]
