# Generated by Django 3.2.23 on 2024-02-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_Created_model_cohort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'verbose_name': 'Когорта', 'verbose_name_plural': 'Когорты'},
        ),
    ]
