# Generated by Django 3.2.23 on 2024-02-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_cohort_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'ordering': ('start_date',), 'verbose_name': 'Группа курса', 'verbose_name_plural': 'Группы курса'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.AddField(
            model_name='cohort',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Не заполняйте это поле, если хотите, чтобы группа была доступна всегда.', null=True, verbose_name='Максимальное количество студентов'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(blank=True, help_text='Не заполняйте это поле, если хотите, чтобы группа была доступна всегда.', null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='start_date',
            field=models.DateField(blank=True, help_text='Не заполняйте это поле, если хотите, чтобы группа была доступна всегда.', null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='students_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Текущее количество студентов'),
        ),
    ]
