# Generated by Django 3.2.23 on 2024-02-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_remove_subscription_unique_cohort_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'ordering': ('start_date',), 'verbose_name': 'Когорта', 'verbose_name_plural': 'Когорты'},
        ),
    ]
