# Generated by Django 3.2.23 on 2024-02-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_cohort_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('Lesson', 'Урок'), ('Videolesson', 'Видеоурок'), ('Webinar', 'Вебинар'), ('Quiz', 'Тест'), ('Homework', 'Домашнее задание')], max_length=20, verbose_name='тип урока'),
        ),
    ]
