# Generated by Django 3.2.23 on 2024-02-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.IntegerField(choices=[(0, 'В разработке'), (1, 'Готов'), (2, 'Опубликован')], db_index=True, default=0, verbose_name='статус урока'),
        ),
    ]
