# Generated by Django 3.2.23 on 2024-02-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(0, 'в разработке'), (1, 'опубликован'), (2, 'в архиве'), (3, 'скрытый')], default=0, verbose_name='статус курса'),
        ),
    ]
