# Generated by Django 3.2.20 on 2024-02-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20240225_1638'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='knowledge',
            name='unique_knowledge',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.direction', verbose_name='Направление умения'),
        ),
        migrations.AddConstraint(
            model_name='knowledge',
            constraint=models.UniqueConstraint(fields=('title', 'direction'), name='unique_knowledge'),
        ),
    ]
