# Generated by Django 3.2.23 on 2024-02-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20240221_1522'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'course'], name='courses_sub_user_id_543e11_idx'),
        ),
    ]
