# Generated by Django 3.2.20 on 2023-10-13 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='start_time',
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.JSONField(default=list, verbose_name='Варианты ответов'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения выполнения'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала выполнения'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quizzes.quiz', verbose_name='Квиз'),
        ),
    ]
