# Generated by Django 3.2.20 on 2023-09-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answers',
            new_name='context',
        ),
    ]
