# Generated by Django 3.2.20 on 2023-09-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.JSONField(default=list, verbose_name='Варианты ответов'),
        ),
    ]
