# Generated by Django 3.2.20 on 2023-09-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_rename_answers_question_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='context',
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Варианты ответов'),
        ),
    ]
