# Generated by Django 3.2.23 on 2024-02-21 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0026_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(verbose_name='Описание вебинара')),
                ('link', models.CharField(max_length=400, verbose_name='Ссылка на вебинар')),
                ('webinar_date', models.DateTimeField(verbose_name='Дата вебинара')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar', to='courses.cohort', verbose_name='Когорта')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Вебинар для когорты',
                'verbose_name_plural': 'Вебинары для когорты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (3, 'APPROVED')], default=0, verbose_name='Статус')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_progress', to='courses.lesson', verbose_name='Урок')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subscription', verbose_name='Подписка')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinars.webinartemplate', verbose_name='Шаблон вебинара')),
            ],
            options={
                'verbose_name': 'Прогресс вебинара',
                'verbose_name_plural': 'Прогресс вебинара',
                'ordering': ['-updated_at'],
            },
        ),
    ]
