# Generated by Django 3.2.23 on 2024-02-21 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0026_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(verbose_name='Описание вебинара')),
                ('link', models.CharField(max_length=400, verbose_name='Ссылка на вебинар')),
                ('webinar_date', models.DateTimeField(verbose_name='Дата вебинара')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar', to='courses.cohort', verbose_name='Когорта')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Вебинар для когорты',
                'verbose_name_plural': 'Вебинары для когорты',
                'ordering': ['-updated_at'],
            },
        ),
    ]
