# Generated by Django 3.2.23 on 2024-02-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание вебинара'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='link',
            field=models.URLField(max_length=400, verbose_name='Ссылка на вебинар'),
        ),
    ]
