# Generated by Django 3.2.23 on 2024-02-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0002_auto_20240222_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='duration',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Длительность вебинара'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='recording_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание записи вебинара'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='recording_link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Запись вебинара'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Запланирован'), (1, 'Завершен')], default=0, verbose_name='Статус вебинара'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание вебинара'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на вебинар'),
        ),
    ]
