# Generated by Django 3.2.20 on 2023-12-17 06:29

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_subscription_enabled'),
        ('users', '0004_auto_20231122_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_category',
            field=models.CharField(choices=[('one_time', 'Разовая'), ('progressive', 'За достижение')], default=1, max_length=20, verbose_name='Тип значка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('manual', 'Ручная'), ('achievement', 'За прохождение')], default=1, max_length=20, verbose_name='Вид значка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='badges/', verbose_name='Изображение значка'),
        ),
        migrations.AddField(
            model_name='badge',
            name='issued_for',
            field=models.CharField(default=1, max_length=255, verbose_name='За что'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='threshold_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Курс для получения'),
        ),
        migrations.AddField(
            model_name='badge',
            name='threshold_courses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество курсов для получения'),
        ),
        migrations.AddField(
            model_name='volunteerbadge',
            name='is_issued',
            field=models.BooleanField(default=True, verbose_name='Выдан или нет'),
        ),
    ]
