# Generated by Django 3.2.20 on 2023-12-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20231122_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('Новичок', 'novice'), ('Бывалый', 'experienced'), ('Профессионал', 'professional')], max_length=20, unique=True, verbose_name='Наименование уровня'),
        ),
    ]
