# Generated by Django 3.2.20 on 2023-12-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20231217_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerbadge',
            name='is_issued',
        ),
        migrations.CreateModel(
            name='VolunteerCourseCompetion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_courses_count', models.PositiveIntegerField(default=0)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_completion', to='users.volunteer')),
            ],
        ),
    ]
