# Generated by Django 3.2.20 on 2024-02-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_level_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yandex_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ЯндексID'),
        ),
    ]
