# Generated by Django 3.2.20 on 2024-02-29 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20240229_2149'),
        ('users', '0007_badge_badge_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.division', verbose_name='Направление умения'),
        ),
        migrations.AddConstraint(
            model_name='badge',
            constraint=models.UniqueConstraint(fields=('name', 'division'), name='unique_badge'),
        ),
    ]
