# Generated by Django 3.2.20 on 2024-03-12 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20240229_2149'),
        ('users', '0008_auto_20240229_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDivisionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Уровень волонтера по направлениям',
                'verbose_name_plural': 'Уровни волонтеров по направлениям',
            },
        ),
        migrations.RemoveConstraint(
            model_name='badge',
            name='unique_badge',
        ),
        migrations.AlterField(
            model_name='badge',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.division', verbose_name='Направление умения'),
        ),
        migrations.AddField(
            model_name='userdivisionlevel',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.division', verbose_name='Направление умения'),
        ),
        migrations.AddField(
            model_name='userdivisionlevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.level', verbose_name='Уровень умения'),
        ),
        migrations.AddField(
            model_name='userdivisionlevel',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_level', to='users.volunteer', verbose_name='Волонтер'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='division_levels',
            field=models.ManyToManyField(blank=True, related_name='volunteers', through='users.UserDivisionLevel', to='courses.Division', verbose_name='Уровень умения'),
        ),
    ]
