# Generated by Django 3.2.23 on 2024-03-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20240229_2149'),
        ('users', '0008_auto_20240229_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='division',
            field=models.ManyToManyField(blank=True, to='courses.Division', verbose_name='Направление курса'),
        ),
    ]
