# Generated by Django 3.2.20 on 2024-03-03 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20240229_2149'),
        ('users', '0008_auto_20240229_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDivisionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.division', verbose_name='Направление умения')),
                ('level', models.ForeignKey(default='novice', on_delete=django.db.models.deletion.PROTECT, to='users.level', verbose_name='Уровень умения')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisionlevels', to='users.volunteer', verbose_name='Волонтер')),
            ],
        ),
        migrations.AddField(
            model_name='volunteer',
            name='divisionlevel',
            field=models.ManyToManyField(blank=True, related_name='volunteers', through='users.UserDivisionLevel', to='courses.Division', verbose_name='Уровень умения'),
        ),
    ]
