# Generated by Django 3.2.23 on 2024-03-13 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20240313_1341'),
        ('users', '0009_auto_20240313_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.division', verbose_name='Направление умения'),
        ),
        migrations.CreateModel(
            name='UserDivisionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.division', verbose_name='Направление умения')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.level', verbose_name='Уровень умения')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_level', to='users.volunteer', verbose_name='Волонтер')),
            ],
            options={
                'verbose_name': 'Уровень волонтера по направлениям',
                'verbose_name_plural': 'Уровни волонтеров по направлениям',
            },
        ),
        migrations.AddField(
            model_name='volunteer',
            name='division_levels',
            field=models.ManyToManyField(blank=True, related_name='volunteers', through='users.UserDivisionLevel', to='courses.Division', verbose_name='Уровень умения'),
        ),
    ]
