# Generated by Django 3.2.23 on 2024-03-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20240313_1341'),
        ('users', '0009_auto_20240313_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='division',
            field=models.ManyToManyField(blank=True, to='courses.Division', verbose_name='Направление курса'),
        ),
    ]
