# Generated by Django 3.2.20 on 2024-03-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20240229_2149'),
        ('users', '0009_auto_20240303_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdivisionlevel',
            options={'verbose_name': 'Уровень волонтера по направлениям', 'verbose_name_plural': 'Уровни волонтеров по направлениям'},
        ),
        migrations.RemoveConstraint(
            model_name='badge',
            name='unique_badge',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='divisionlevel',
            new_name='divisionlevels',
        ),
        migrations.AlterField(
            model_name='badge',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.division', verbose_name='Направление умения'),
        ),
        migrations.AlterField(
            model_name='userdivisionlevel',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.division', verbose_name='Направление умения'),
        ),
        migrations.AlterField(
            model_name='userdivisionlevel',
            name='level',
            field=models.ForeignKey(default='novice', on_delete=django.db.models.deletion.CASCADE, to='users.level', verbose_name='Уровень умения'),
        ),
        migrations.AlterField(
            model_name='userdivisionlevel',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisionlevel', to='users.volunteer', verbose_name='Волонтер'),
        ),
    ]
