# Generated by Django 3.2.23 on 2024-02-09 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0022_alter_cohort_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Черновик'), (1, 'Отправлено'), (2, 'На проверке'), (3, 'Одобрено'), (4, 'Отклонено'), (5, 'Отменено')], default=0, verbose_name='Статус')),
                ('text', models.CharField(max_length=10000, verbose_name='Текст задания')),
                ('required', models.BooleanField(default=True, verbose_name='Обязательное задание')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Урок')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['-updated_at'],
            },
        ),
    ]
