# Generated by Django 3.2.23 on 2024-02-15 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_lesson_lesson_type'),
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='courses.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено'), ('in_review', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
