# Generated by Django 3.2.20 on 2024-02-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0003_alter_homework_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Черновик'), (1, 'Отправлено'), (2, 'На проверке'), (3, 'Одобрено'), (4, 'Отклонено'), (5, 'Отменено')], default=0, verbose_name='Статус'),
        ),
    ]
