# Generated by Django 3.2.12 on 2022-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название курса')),
                ('format', models.CharField(max_length=60, verbose_name='Формат курса')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала курса')),
                ('cover_path', models.FileField(blank=True, null=True, upload_to='', verbose_name='Путь к обложке курса')),
                ('short_description', models.CharField(max_length=120, verbose_name='Краткое описание курса')),
                ('full_description', models.TextField(verbose_name='Полное описание курса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания курса')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=50, verbose_name='Статус курса')),
                ('slug', models.SlugField(editable=False, max_length=20)),
            ],
            options={
                'verbose_name': 'Статус курса',
                'verbose_name_plural': 'Статус курсов',
                'db_table': 'course_status',
            },
        ),
    ]
