# Generated by Django 3.2.15 on 2022-09-11 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogressstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userlessonstatus', to=settings.AUTH_USER_MODEL, verbose_name='userlessonstatus'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_creator', to=settings.AUTH_USER_MODEL, verbose_name='пользователь, создавший урок'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='user_modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_editor', to=settings.AUTH_USER_MODEL, verbose_name='пользователь, внёсший изменения в урок'),
        ),
        migrations.AddField(
            model_name='courseprogressstatus',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_progress', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseprogressstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usercoursestatus', to=settings.AUTH_USER_MODEL, verbose_name='coursestatus'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course', to='users.level', verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='course',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создатель курса'),
        ),
        migrations.AddField(
            model_name='chapterprogressstatus',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapter_progress', to='courses.chapter'),
        ),
        migrations.AddField(
            model_name='chapterprogressstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userchapterstatus', to=settings.AUTH_USER_MODEL, verbose_name='userchapterstatus'),
        ),
        migrations.AddField(
            model_name='chapterlesson',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.chapter'),
        ),
        migrations.AddField(
            model_name='chapterlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='courses.course', verbose_name='Части'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='lessons',
            field=models.ManyToManyField(through='courses.ChapterLesson', to='courses.Lesson', verbose_name='уроки главы'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapter_creator', to=settings.AUTH_USER_MODEL, verbose_name='пользователь, создавший главу'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='user_modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapter_editor', to=settings.AUTH_USER_MODEL, verbose_name='пользователь, внёсший изменения в главу'),
        ),
        migrations.AddConstraint(
            model_name='chapterlesson',
            constraint=models.UniqueConstraint(fields=('chapter', 'lesson', 'order_number'), name='unique_chapter_lesson'),
        ),
    ]
