# Generated by Django 3.2.12 on 2022-05-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_user_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=50, verbose_name='Статус курса')),
                ('slug', models.SlugField(editable=False, max_length=20)),
            ],
            options={
                'verbose_name': 'Статус курса',
                'verbose_name_plural': 'Статус курсов',
                'db_table': 'course_status',
            },
        ),
    ]
