name: Deploy to Remote Server
on:
  workflow_run:
    workflows: ["Code Style Checks & Tests"]
    types:
      - completed
    branches:
      - master
      - dev

jobs:
  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build lizaalert_backend-base image
        run: docker build -t local/lizaalert_backend-base -f services/base/Dockerfile .

      - name: Build lizaalert_backend image
        run: docker build -t local/lizaalert_backend -f services/local/Dockerfile .

      - name: Log in to Yandex Container Registry
        env:
          YCR_PRIVATE_KEY: ${{ secrets.YCR_PRIVATE_KEY }}
        run: echo "$YCR_PRIVATE_KEY" | docker login --username json_key --password-stdin cr.yandex

      - name: Build and Push Docker image
        run: |
          docker tag local/lizaalert_backend cr.yandex/crpabbati0r6r7i5ee8c/lizaalert_backend:latest
          docker push cr.yandex/crpabbati0r6r7i5ee8c/lizaalert_backend:latest
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            sudo docker pull cr.yandex/crpabbati0r6r7i5ee8c/lizaalert_backend:latest
            sudo bash -c "docker-compose -f /root/liza_backend/docker-compose.yml up -d"
            sudo bash -c "docker-compose -f /root/liza_backend/docker-compose.yml exec -T backend python manage.py migrate"
