name: Code Style Checks & Tests
on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Flake8 check
        run: poetry run flake8 .

      - name: Isort check
        run: poetry run isort --check-only --skip-gitignore .

      - name: Black check
        run: poetry run black --check .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build and run app
        run: |
          cp lizaalert-backend/env.sample lizaalert-backend/.env
          cp services/postgres/env.sample services/postgres/.env
          docker-compose up -d
          sleep 20

      - name: Run tests
        run: docker-compose exec -T backend pytest tests/
